site_name: Eke PTI Záróvizsga Tételek
site_url: https://csicsi2000.github.io/zarotetelek/
theme: 
  name: material
  palette:
    scheme: 'slate'
    #primary: purple
    accent: light purple
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'images/book.png'
  #favicon: 'images/book.png'
  search: true
plugins:
  - search
  - awesome-pages
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences